[package]
name = "smb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
byteorder = "1.4"
asn1-rs = "0.6.2"
ntlmclient = { path = "src/ntlmclient-0.1.0" }
hex = "*"
base64 = "*"
bitflags = "2.6.0"
hmac = "0.12.1"
md5 = "*"
anyhow = "*"