[package]
name = "smb2-rs"
version = "0.1.0"
edition = "2024"
authors = ["Akatsuki"]
description = "A library for smb2.1 authentication."
license = "MIT OR Apache-2.0"
homepage = "https://github.com/Schira4396/smb2-rs"
repository = "https://github.com/Schira4396/smb2-rs"
documentation = "https://github.com/Schira4396/smb2-rs"




[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
byteorder = "1.4"
asn1-rs = "0.6.2"
ntlmclient = "*"
hex = "*"
base64 = "*"
bitflags = "2.6.0"
hmac = "0.12.1"
md5 = "*"
anyhow = "*"